#!/bin/bash
#
# nodes - the number of computer nodes in the job
# ppn   - the number of MPI processes per node (ppn!)
# the total number of processes is nodes*ppn
#
#PBS -l nodes=1:ppn=1,walltime=00:10:00
#PBS -q dev_q
#PBS -N scf
#PBS -W group_list=training
#PBS -A training
#PBS -l advres=SICM2.29

cd $PBS_O_WORKDIR

for nth in 16 14 12 10 8 6 4 2 1 ; do 
   OMP_NUM_THREADS=$nth ./scf c6h12.xyz
done



