
CXX = icpc
CXXFLAGS = -qopenmp
TARGETS = hello hello_for num_thr num_thr_parallel num_thr_nested num_thr_nested2 setvec

all:	$(TARGETS)

.PHONY:
clean:
	/bin/rm -f $(TARGETS) *.o core* *~  BeingGenial.e* BeingGenial.o*
